// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AuthorizationSpecApplyConfiguration represents a declarative configuration of the AuthorizationSpec type for use
// with apply.
type AuthorizationSpecApplyConfiguration struct {
	DynamicClientRegistration *DynamicClientRegistrationSpecApplyConfiguration `json:"dynamicClientRegistration,omitempty"`
}

// AuthorizationSpecApplyConfiguration constructs a declarative configuration of the AuthorizationSpec type for use with
// apply.
func AuthorizationSpec() *AuthorizationSpecApplyConfiguration {
	return &AuthorizationSpecApplyConfiguration{}
}

// WithDynamicClientRegistration sets the DynamicClientRegistration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DynamicClientRegistration field is set to the value of the last call.
func (b *AuthorizationSpecApplyConfiguration) WithDynamicClientRegistration(value *DynamicClientRegistrationSpecApplyConfiguration) *AuthorizationSpecApplyConfiguration {
	b.DynamicClientRegistration = value
	return b
}
