// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DynamicClientRegistrationSpecApplyConfiguration represents a declarative configuration of the DynamicClientRegistrationSpec type for use
// with apply.
type DynamicClientRegistrationSpecApplyConfiguration struct {
	PublicClient *bool `json:"publicClient,omitempty"`
}

// DynamicClientRegistrationSpecApplyConfiguration constructs a declarative configuration of the DynamicClientRegistrationSpec type for use with
// apply.
func DynamicClientRegistrationSpec() *DynamicClientRegistrationSpecApplyConfiguration {
	return &DynamicClientRegistrationSpecApplyConfiguration{}
}

// WithPublicClient sets the PublicClient field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PublicClient field is set to the value of the last call.
func (b *DynamicClientRegistrationSpecApplyConfiguration) WithPublicClient(value bool) *DynamicClientRegistrationSpecApplyConfiguration {
	b.PublicClient = &value
	return b
}
