// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MCPGatewaySpecApplyConfiguration represents a declarative configuration of the MCPGatewaySpec type for use
// with apply.
type MCPGatewaySpecApplyConfiguration struct {
	OrganizationID   *string                              `json:"organizationId,omitempty"`
	OrganizationName *string                              `json:"organizationName,omitempty"`
	CustomDomain     *string                              `json:"customDomain,omitempty"`
	Authorization    *AuthorizationSpecApplyConfiguration `json:"authorization,omitempty"`
	Projects         []ProjectSpecApplyConfiguration      `json:"projects,omitempty"`
}

// MCPGatewaySpecApplyConfiguration constructs a declarative configuration of the MCPGatewaySpec type for use with
// apply.
func MCPGatewaySpec() *MCPGatewaySpecApplyConfiguration {
	return &MCPGatewaySpecApplyConfiguration{}
}

// WithOrganizationID sets the OrganizationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OrganizationID field is set to the value of the last call.
func (b *MCPGatewaySpecApplyConfiguration) WithOrganizationID(value string) *MCPGatewaySpecApplyConfiguration {
	b.OrganizationID = &value
	return b
}

// WithOrganizationName sets the OrganizationName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OrganizationName field is set to the value of the last call.
func (b *MCPGatewaySpecApplyConfiguration) WithOrganizationName(value string) *MCPGatewaySpecApplyConfiguration {
	b.OrganizationName = &value
	return b
}

// WithCustomDomain sets the CustomDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CustomDomain field is set to the value of the last call.
func (b *MCPGatewaySpecApplyConfiguration) WithCustomDomain(value string) *MCPGatewaySpecApplyConfiguration {
	b.CustomDomain = &value
	return b
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *MCPGatewaySpecApplyConfiguration) WithAuthorization(value *AuthorizationSpecApplyConfiguration) *MCPGatewaySpecApplyConfiguration {
	b.Authorization = value
	return b
}

// WithProjects adds the given value to the Projects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Projects field.
func (b *MCPGatewaySpecApplyConfiguration) WithProjects(values ...*ProjectSpecApplyConfiguration) *MCPGatewaySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProjects")
		}
		b.Projects = append(b.Projects, *values[i])
	}
	return b
}
